# -*- coding: utf-8 -*-
"""示例数据（7 天真实记录），供离线预览 / Web 演示模式复用。
   直接运行可在命令行预览： python demo.py"""
import config


def sample_rows():
    """返回 (follow_rows, data_rows)，字段名取自 config 的真实列名映射。
       覆盖 2026-05-30 ~ 2026-06-05，含告警事件供红色告警区演示。"""
    F, D = config.FOLLOW_FIELDS, config.DATA_FIELDS

    # ===== 跟播记录（简化：每天 A~E 各一条）=====
    follow_rows = [
        # ---- 05-30（周六）----
        {F["date"]: "2026-05-30", F["slot"]: "A", F["operator"]: "邓安祺", F["anchor"]: "苑含笑",
         F["coefficient"]: "无调整", F["material"]: "主力素材无变化",
         F["delivery"]: "拉通主播加量起量情况",
         F["volume"]: "无调整", F["abnormal"]: "否", F["platform_activity"]: "无"},
        {F["date"]: "2026-05-30", F["slot"]: "B", F["operator"]: "邓安祺", F["anchor"]: "张新",
         F["coefficient"]: "无调整", F["material"]: "主力素材无变化",
         F["delivery"]: "拉通主播加量起量情况",
         F["volume"]: "无调整", F["abnormal"]: "否", F["platform_activity"]: "无"},
        {F["date"]: "2026-05-30", F["slot"]: "C", F["operator"]: "张宇霆", F["anchor"]: "兼职文静",
         F["coefficient"]: "无调整", F["material"]: "主力素材跑量稳定",
         F["delivery"]: "控成本测试",
         F["volume"]: "无调整", F["abnormal"]: "否", F["platform_activity"]: "无"},
        {F["date"]: "2026-05-30", F["slot"]: "D", F["operator"]: "邢世坦", F["anchor"]: "赵颢棋",
         F["coefficient"]: "第三小时系数提到7.5",
         F["material"]: "高消耗素材出单效率始终不高",
         F["delivery"]: "拉流流速和高消耗素材出单情况",
         F["volume"]: "无调整", F["abnormal"]: "否", F["platform_activity"]: "无"},
        {F["date"]: "2026-05-30", F["slot"]: "E", F["operator"]: "邢世坦", F["anchor"]: "范晓晶",
         F["coefficient"]: "无调整", F["material"]: "换播后素材出单效率会好一点",
         F["delivery"]: "持续加量",
         F["volume"]: "无调整", F["abnormal"]: "否", F["platform_activity"]: "无"},

        # ---- 05-31（周日）----
        {F["date"]: "2026-05-31", F["slot"]: "A", F["operator"]: "邓安祺", F["anchor"]: "张新",
         F["coefficient"]: "无调整", F["material"]: "开播后画面主要出单，素材出单较少",
         F["delivery"]: "拉通主播加量起量情况",
         F["volume"]: "无调整", F["abnormal"]: "否", F["platform_activity"]: "无"},
        {F["date"]: "2026-05-31", F["slot"]: "B", F["operator"]: "邓安祺,张宇霆", F["anchor"]: "邹楠楠",
         F["coefficient"]: "无调整", F["material"]: "主力素材无变化",
         F["delivery"]: "拉通主播加量起量情况",
         F["volume"]: "无调整", F["abnormal"]: "否", F["platform_activity"]: "无"},
        {F["date"]: "2026-05-31", F["slot"]: "C", F["operator"]: "张宇霆", F["anchor"]: "范晓晶",
         F["coefficient"]: "无调整", F["material"]: "主力素材无变化",
         F["delivery"]: "控成本测试",
         F["volume"]: "无调整", F["abnormal"]: "否", F["platform_activity"]: "无"},
        {F["date"]: "2026-05-31", F["slot"]: "D", F["operator"]: "张宇霆,贾明芳", F["anchor"]: "赵颢棋",
         F["coefficient"]: "8点后系数调至7.5",
         F["material"]: "主力素材跑量稳定",
         F["delivery"]: "控成本测试",
         F["volume"]: "21点系统掉量手动加量", F["abnormal"]: "否",
         F["platform_activity"]: "618消费券（满300-40）"},
        {F["date"]: "2026-05-31", F["slot"]: "E", F["operator"]: "贾明芳", F["anchor"]: "朱佳琪",
         F["coefficient"]: "23点系数调至7.3",
         F["material"]: "主力素材无变化",
         F["delivery"]: "控成本测试",
         F["volume"]: "持续加量操作", F["abnormal"]: "否", F["platform_activity"]: "无"},

        # ---- 06-01（周一）⚠️ 有告警 ----
        {F["date"]: "2026-06-01", F["slot"]: "A", F["operator"]: "邓安祺", F["anchor"]: "兼职王小宇",
         F["coefficient"]: "第二小时系数调整到7.5",
         F["material"]: "主力素材无变化",
         F["delivery"]: "控成本测试",
         F["volume"]: "除开播第一小时加量无加量动作",
         F["abnormal"]: "否", F["platform_activity"]: "无"},
        {F["date"]: "2026-06-01", F["slot"]: "B", F["operator"]: "邓安祺", F["anchor"]: "邹楠楠",
         F["coefficient"]: "换播后第一小时转化不稳定系数提到7.7",
         F["material"]: "主力素材无变化",
         F["delivery"]: "控成本测试",
         F["volume"]: "最后一小时转化上升进行加量",
         F["abnormal"]: "否", F["platform_activity"]: "无"},
        {F["date"]: "2026-06-01", F["slot"]: "C", F["operator"]: "贾明芳", F["anchor"]: "兼职文静",
         F["coefficient"]: "换播后第一小时转化走低，系数提至7.9",
         F["material"]: "主力素材无变化",
         F["delivery"]: "控成本测试",
         F["volume"]: "无调整",
         F["abnormal"]: "是",
         F["abnormal_note"]: "主播有些体力不支，后续嗓子疼",
         F["anchor_status_abnormal"]: "是",
         F["anchor_status_note"]: "主播有些体力不支，后续嗓子疼",
         F["platform_activity"]: "618消费券（满300-40）"},
        {F["date"]: "2026-06-01", F["slot"]: "D", F["operator"]: "张宇霆", F["anchor"]: "赵颢棋",
         F["coefficient"]: "无调整",
         F["material"]: "主力素材无变化",
         F["delivery"]: "控成本测试",
         F["volume"]: "无调整", F["abnormal"]: "否",
         F["platform_activity"]: "618消费券（满300-40）"},
        {F["date"]: "2026-06-01", F["slot"]: "E", F["operator"]: "张宇霆", F["anchor"]: "朱佳琪",
         F["coefficient"]: "无调整",
         F["material"]: "主力素材无变化",
         F["delivery"]: "控成本测试",
         F["volume"]: "在22点起量后转化都很高，第二小时追加起量，过了12点1点取消了",
         F["abnormal"]: "否",
         F["platform_activity"]: "618消费券（满300-40）过了12点无了"},

        # ---- 06-02（周二）⚠️ 有告警 ----
        {F["date"]: "2026-06-02", F["slot"]: "A", F["operator"]: "邓安祺", F["anchor"]: "乔莹",
         F["coefficient"]: "第三小时系数调整7.6",
         F["material"]: "主力素材无变化",
         F["delivery"]: "控成本测试",
         F["volume"]: "开播加量",
         F["abnormal"]: "是",
         F["abnormal_note"]: "身体不舒服，头脑思路不清晰",
         F["anchor_status_abnormal"]: "是",
         F["anchor_status_note"]: "身体不舒服，头脑思路不清晰；逼单话术需提升，统一回复公屏容易被带偏",
         F["platform_activity"]: "无"},
        {F["date"]: "2026-06-02", F["slot"]: "B", F["operator"]: "邓安祺", F["anchor"]: "苑含笑",
         F["coefficient"]: "第三小时系数调整到7.8",
         F["material"]: "主力素材有变，老主力素材跑量",
         F["delivery"]: "控成本测试",
         F["volume"]: "换播后进行起量，最后一小时转化下滑进行控量",
         F["abnormal"]: "否", F["platform_activity"]: "无"},
        {F["date"]: "2026-06-02", F["slot"]: "C", F["operator"]: "贾明芳", F["anchor"]: "兼职马甜甜",
         F["coefficient"]: "第二小时系数调至7.6",
         F["material"]: "主力素材无变化",
         F["delivery"]: "控成本测试",
         F["volume"]: "新素材信号ID：7646214283027595300",
         F["abnormal"]: "否", F["platform_activity"]: "无"},
        {F["date"]: "2026-06-02", F["slot"]: "D", F["operator"]: "张宇霆", F["anchor"]: "范晓晶",
         F["coefficient"]: "无调整",
         F["material"]: "主力素材无变化",
         F["delivery"]: "控成本测试",
         F["volume"]: "起量高roi的时候加起量了",
         F["abnormal"]: "否", F["platform_activity"]: "无"},
        {F["date"]: "2026-06-02", F["slot"]: "E", F["operator"]: "张宇霆", F["anchor"]: "张新",
         F["coefficient"]: "第二小时调为7.3",
         F["material"]: "主力素材无变化",
         F["delivery"]: "控成本测试",
         F["volume"]: "起量持续加了",
         F["abnormal"]: "否", F["platform_activity"]: "无"},

        # ---- 06-03（周三）----
        {F["date"]: "2026-06-03", F["slot"]: "A", F["operator"]: "贾明芳", F["anchor"]: "苑含笑",
         F["coefficient"]: "第二小时系数调至7；第三小时调至7.3",
         F["material"]: "主力素材无变化",
         F["delivery"]: "控成本测试",
         F["volume"]: "刚开播加量，其余时间未加量",
         F["abnormal"]: "否", F["platform_activity"]: "无"},
        {F["date"]: "2026-06-03", F["slot"]: "B", F["operator"]: "贾明芳", F["anchor"]: "邹楠楠",
         F["coefficient"]: "第二小时系数调至7.5；第三小时调至7.8",
         F["material"]: "主力素材无变化",
         F["delivery"]: "控成本测试",
         F["volume"]: "未加量，系统起量；控量10分钟",
         F["abnormal"]: "否", F["platform_activity"]: "无"},
        {F["date"]: "2026-06-03", F["slot"]: "C", F["operator"]: "吴家伟", F["anchor"]: "试播单楚陵",
         F["coefficient"]: "无调整，按照7.8继续跑",
         F["material"]: "主力素材无变化",
         F["delivery"]: "控成本测试",
         F["volume"]: "加入三条素材测试",
         F["abnormal"]: "否", F["platform_activity"]: "无"},
        {F["date"]: "2026-06-03", F["slot"]: "D", F["operator"]: "邢世坦", F["anchor"]: "赵颢棋",
         F["coefficient"]: "8点半系数调整到7.8；9点半调至7.5",
         F["material"]: "主力素材跑量",
         F["delivery"]: "控成本测试",
         F["volume"]: "提完系数后，9点流速180，追600",
         F["abnormal"]: "否", F["platform_activity"]: "无"},
        {F["date"]: "2026-06-03", F["slot"]: "E", F["operator"]: "邢世坦", F["anchor"]: "范晓晶",
         F["coefficient"]: "无调整，系数7.5",
         F["material"]: "主力素材无变化",
         F["delivery"]: "控成本测试",
         F["volume"]: "换播后流速低，追500；11点后流速下滑，追700",
         F["abnormal"]: "否", F["platform_activity"]: "无"},

        # ---- 06-04（周四）----
        {F["date"]: "2026-06-04", F["slot"]: "A", F["operator"]: "贾明芳", F["anchor"]: "乔莹",
         F["coefficient"]: "无调整", F["material"]: "主力素材无变化",
         F["delivery"]: "控成本测试",
         F["volume"]: "无调整", F["abnormal"]: "否", F["platform_activity"]: "无"},
        {F["date"]: "2026-06-04", F["slot"]: "B", F["operator"]: "贾明芳,张佳林", F["anchor"]: "苑含笑",
         F["coefficient"]: "无调整",
         F["material"]: "主力素材有变，老主力素材跑量，12点后近20分钟未出单",
         F["delivery"]: "控成本测试",
         F["volume"]: "未加量；持续系统起量",
         F["abnormal"]: "否", F["platform_activity"]: "无"},
        {F["date"]: "2026-06-04", F["slot"]: "C", F["operator"]: "张佳林", F["anchor"]: "张新",
         F["coefficient"]: "第二小时调整到7.2",
         F["material"]: "下掉南方素材",
         F["delivery"]: "控成本测试",
         F["volume"]: "无调整", F["abnormal"]: "否", F["platform_activity"]: "无"},
        {F["date"]: "2026-06-04", F["slot"]: "D", F["operator"]: "邓安祺", F["anchor"]: "赵颢棋",
         F["coefficient"]: "第一小时调整到7.5",
         F["material"]: "添加南方素材",
         F["delivery"]: "控成本测试",
         F["volume"]: "无调整", F["abnormal"]: "否", F["platform_activity"]: "无"},
        {F["date"]: "2026-06-04", F["slot"]: "E", F["operator"]: "邓安祺", F["anchor"]: "范晓晶",
         F["coefficient"]: "无调整", F["material"]: "主力素材无变化",
         F["delivery"]: "控成本测试",
         F["volume"]: "无调整", F["abnormal"]: "否", F["platform_activity"]: "无"},

        # ---- 06-05（周五·今天）----
        {F["date"]: "2026-06-05", F["slot"]: "A", F["operator"]: "贾明芳", F["anchor"]: "熊怡芯",
         F["coefficient"]: "", F["material"]: "",
         F["delivery"]: "", F["volume"]: "", F["abnormal"]: "否", F["platform_activity"]: ""},
        {F["date"]: "2026-06-05", F["slot"]: "B", F["operator"]: "张佳林", F["anchor"]: "苑含笑",
         F["coefficient"]: "", F["material"]: "",
         F["delivery"]: "", F["volume"]: "", F["abnormal"]: "否", F["platform_activity"]: ""},
        {F["date"]: "2026-06-05", F["slot"]: "C", F["operator"]: "张佳林", F["anchor"]: "张新",
         F["coefficient"]: "", F["material"]: "",
         F["delivery"]: "", F["volume"]: "", F["abnormal"]: "否", F["platform_activity"]: ""},
        {F["date"]: "2026-06-05", F["slot"]: "D", F["operator"]: "邓安祺", F["anchor"]: "",
         F["coefficient"]: "", F["material"]: "",
         F["delivery"]: "", F["volume"]: "", F["abnormal"]: "否", F["platform_activity"]: ""},
        {F["date"]: "2026-06-05", F["slot"]: "E", F["operator"]: "邓安祺", F["anchor"]: "",
         F["coefficient"]: "", F["material"]: "",
         F["delivery"]: "", F["volume"]: "", F["abnormal"]: "否", F["platform_activity"]: ""},
    ]

    # ===== 直播数据（每天 A~E 各一条）=====
    data_rows = [
        # 05-30 周六（周最佳日 ¥508,500）
        {D["date"]: "2026-05-30", D["slot"]: "A", D["gmv"]: "94300", D["roi"]: "7.02", D["conv_rate"]: "0.0013"},
        {D["date"]: "2026-05-30", D["slot"]: "B", D["gmv"]: "133400", D["roi"]: "6.92", D["conv_rate"]: "0.0018"},
        {D["date"]: "2026-05-30", D["slot"]: "C", D["gmv"]: "100900", D["roi"]: "6.86", D["conv_rate"]: "0.0025"},
        {D["date"]: "2026-05-30", D["slot"]: "D", D["gmv"]: "92400", D["roi"]: "7.33", D["conv_rate"]: "0.0033"},
        {D["date"]: "2026-05-30", D["slot"]: "E", D["gmv"]: "87500", D["roi"]: "8.33", D["conv_rate"]: "0.0032"},
        # 05-31 周日
        {D["date"]: "2026-05-31", D["slot"]: "A", D["gmv"]: "68900", D["roi"]: "6.84", D["conv_rate"]: "0.0011"},
        {D["date"]: "2026-05-31", D["slot"]: "B", D["gmv"]: "101100", D["roi"]: "6.84", D["conv_rate"]: "0.0016"},
        {D["date"]: "2026-05-31", D["slot"]: "C", D["gmv"]: "107700", D["roi"]: "7.52", D["conv_rate"]: "0.003"},
        {D["date"]: "2026-05-31", D["slot"]: "D", D["gmv"]: "98500", D["roi"]: "7.01", D["conv_rate"]: "0.0032"},
        {D["date"]: "2026-05-31", D["slot"]: "E", D["gmv"]: "91100", D["roi"]: "8.52", D["conv_rate"]: "0.0032"},
        # 06-01 周一
        {D["date"]: "2026-06-01", D["slot"]: "A", D["gmv"]: "58000", D["roi"]: "6.05", D["conv_rate"]: "0.0009"},
        {D["date"]: "2026-06-01", D["slot"]: "B", D["gmv"]: "84000", D["roi"]: "7.60", D["conv_rate"]: "0.002"},
        {D["date"]: "2026-06-01", D["slot"]: "C", D["gmv"]: "74100", D["roi"]: "7.64", D["conv_rate"]: "0.0022"},
        {D["date"]: "2026-06-01", D["slot"]: "D", D["gmv"]: "91000", D["roi"]: "7.95", D["conv_rate"]: "0.0028000000000000004"},
        {D["date"]: "2026-06-01", D["slot"]: "E", D["gmv"]: "91100", D["roi"]: "8.52", D["conv_rate"]: "0.0032"},
        # 06-02 周二
        {D["date"]: "2026-06-02", D["slot"]: "A", D["gmv"]: "45200", D["roi"]: "5.80", D["conv_rate"]: "0.0008"},
        {D["date"]: "2026-06-02", D["slot"]: "B", D["gmv"]: "78700", D["roi"]: "7.12", D["conv_rate"]: "0.0019"},
        {D["date"]: "2026-06-02", D["slot"]: "C", D["gmv"]: "69300", D["roi"]: "7.45", D["conv_rate"]: "0.0021"},
        {D["date"]: "2026-06-02", D["slot"]: "D", D["gmv"]: "75200", D["roi"]: "7.88", D["conv_rate"]: "0.0026"},
        {D["date"]: "2026-06-02", D["slot"]: "E", D["gmv"]: "64300", D["roi"]: "8.40", D["conv_rate"]: "0.003"},
        # 06-03 周三
        {D["date"]: "2026-06-03", D["slot"]: "A", D["gmv"]: "63600", D["roi"]: "6.55", D["conv_rate"]: "0.0011"},
        {D["date"]: "2026-06-03", D["slot"]: "B", D["gmv"]: "95800", D["roi"]: "7.20", D["conv_rate"]: "0.0018"},
        {D["date"]: "2026-06-03", D["slot"]: "C", D["gmv"]: "72300", D["roi"]: "7.10", D["conv_rate"]: "0.0023"},
        {D["date"]: "2026-06-03", D["slot"]: "D", D["gmv"]: "89100", D["roi"]: "7.65", D["conv_rate"]: "0.0028000000000000004"},
        {D["date"]: "2026-06-03", D["slot"]: "E", D["gmv"]: "82900", D["roi"]: "8.10", D["conv_rate"]: "0.0031"},
        # 06-04 周四
        {D["date"]: "2026-06-04", D["slot"]: "A", D["gmv"]: "25400", D["roi"]: "6.37", D["conv_rate"]: "0.0015"},
        {D["date"]: "2026-06-04", D["slot"]: "B", D["gmv"]: "75500", D["roi"]: "7.57", D["conv_rate"]: "0.0023"},
        {D["date"]: "2026-06-04", D["slot"]: "C", D["gmv"]: "68500", D["roi"]: "7.92", D["conv_rate"]: "0.0027"},
        {D["date"]: "2026-06-04", D["slot"]: "D", D["gmv"]: "80800", D["roi"]: "7.96", D["conv_rate"]: "0.0027"},
        {D["date"]: "2026-06-04", D["slot"]: "E", D["gmv"]: "54700", D["roi"]: "7.36", D["conv_rate"]: "0.0023"},
        # 06-05 周五（今天，数据未录入）
        {D["date"]: "2026-06-05", D["slot"]: "A", D["gmv"]: "0", D["roi"]: "0", D["conv_rate"]: "0.0"},
        {D["date"]: "2026-06-05", D["slot"]: "B", D["gmv"]: "0", D["roi"]: "0", D["conv_rate"]: "0.0"},
        {D["date"]: "2026-06-05", D["slot"]: "C", D["gmv"]: "0", D["roi"]: "0", D["conv_rate"]: "0.0"},
        {D["date"]: "2026-06-05", D["slot"]: "D", D["gmv"]: "0", D["roi"]: "0", D["conv_rate"]: "0.0"},
        {D["date"]: "2026-06-05", D["slot"]: "E", D["gmv"]: "0", D["roi"]: "0", D["conv_rate"]: "0.0"},
    ]
    return follow_rows, data_rows


if __name__ == "__main__":
    from report import build_report
    f, d = sample_rows()
    title, text = build_report("2026-06-04", f, d)
    print("TITLE:", title)
    print("=" * 60)
    print(text)
